# This CI workflow will run any time any of the code files within the 03-nlp directory get updated
name: 03 NLP CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - "03-nlp/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "03-nlp/**"
  workflow_dispatch:
    
jobs:
  ci:
    # strategy:
    #   matrix:
    #     proj: [ 03-nlp/01-TranslateText/TranslateText.csproj]
    uses: ./.github/workflows/00-reusable-ci.yml
    with:
      project: 04-aoai/App/App.csproj