# This CI workflow will run any time any of the code files within the 03-nlp directory get updated
name: 03 NLP CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - "03-nlp/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "03-nlp/**"
  workflow_dispatch:
    
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: CD into 03-nlp directory
      run: cd 03-nlp
    
    - name: CD into 01-TranslateText directory
      run: cd 01-TranslateText
    
    - name: List files in current directory
      run: ls -la
        
    - name: Restore dependencies
      run: dotnet restore 03-nlp/01-TranslateText/TranslateText.csproj
      
    - name: Build
      run: dotnet build --no-restore 03-nlp/01-TranslateText/TranslateText.csproj
